language: node_js
node_js:
  - lts
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script: 'yarn workspace react-katex test'
after_success: 'yarn workspace react-katex report-coverage'
